#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Reboot into Windows
if [[ $HOST == "laptop" ]]; then
	alias win="sudo grub-reboot 0 && reboot"
else
	alias win="sudo grub-reboot 2 && reboot"
fi

# Update grub
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Alias sudo
alias sudo="sudo "

# UPatras VPN
alias upvpn="sudo openvpn --config ${XDG_CONFIG_HOME:-$HOME/.config}/openvpn/UPatras.ovpn --daemon"
alias killvpn="sudo pkill openvpn"

# Verbosity and settings that you are pretty much just always going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	rmdir="rmdir -v"\
	rcp="rsync -v --progress"\
	rmv="rsync -v --progress --remove-source-files"\
	ln="ln -v"\
	chmod="chmod -c"\
	chown="chown -c"

# Colorize commands when possible.
alias \
	ls="ls -lhNF --color=auto --group-directories-first" \
	la="ls -lAhNF --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	fgrep="fgrep --color=auto" \
	egrep="grep --color=auto -E" \
	diff="diff --color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR"

# Config shortcuts
alias \
	cfz="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshrc" \
	cfa="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" \
	cfx="$EDITOR ${HOME}/.xinitrc" \
	cfp="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" \
	cfxp="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" \
	cfxr="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xressources" \
	cfv="$EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/"

# Dotfile repo shortcut
alias dots="/usr/bin/git --git-dir=$HOME/.files/ --work-tree=$HOME"

# Wake up HomePC
alias wakeup="wol -i alkalyss.gr d4:3d:7e:dd:0c:64 -p 9"
