#!/bin/sh

#[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

xsetroot -cursor_name left_ptr
xset r rate 300 50	# Speed xrate up
xset m 3/2 0		# Disable acceleration
xkbset -bo 35

# Setup keyboard
setxkbmap \
	-model pc104 \
	-option "caps:super, grp:win_space_toggle, terminate:ctrl_alt_bksp" \
	"us, gr"
killall xcape 2> /dev/null ; xcape -e 'Super_L=Escape' # When super is pressed once treat as escape

# Use Xresources colors/settings on startup
lxsession &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xressources
dunst &			# dunst for notifications
numlockx on 		# Turn on NumLock
picom --experimental-backends &
/home/alkinoos/.fehbg

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

session=${1:-qtile}

case $session in
	kde	) exec startplasma-x11;;
	bspwm	) exec bspwm;;
	awesome ) exec awesome;;
	leftwm	) exec dbus-launch leftwm;;
	openbox	) exec /usr/bin/openbox;;
	qtile	) exec qtile start;;
	*	) exec ${1};;
esac
