#!/bin/sh

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

session=${1:-qtile}

case $session in
	kde	) exec startplasma-x11;;
	bspwm	) exec bspwm;;
	awesome ) exec awesome;;
	leftwm	) exec dbus-launch leftwm;;
	openbox	) exec /usr/bin/openbox;;
	qtile	) exec qtile start;;
	*	) exec ${1};;
esac
