#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#setbg &		# set the background with the `setbg` script
setxkbmap -option caps:escape & # Map CapsLock to Esc
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
#dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
numlockx on 		# Turn on NumLock
#xcompmgr &		# xcompmgr for transparency
