#!/bin/sh

xsetroot -cursor_name left_ptr
xset r rate 300 50	# Speed xrate up
xset m 3/2 0		# Disable acceleration

killall xcape 2> /dev/null ; xcape -e 'Super_L=Escape' # When super is pressed once treat as escape

xinput --map-to-output "Wacom HID 5218 Pen stylus" eDP
xinput --map-to-output "Wacom HID 5218 Finger touch" eDP
xinput --map-to-output "Wacom HID 5218 Pen eraser" eDP

lxsession &
# Use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xressources &
dunst &			# dunst for notifications
numlockx on & 		# Turn on NumLock
unclutter --timeout 5 --exclude-root --ignore-scrolling --hide-on-touch &
picom --experimental-backends &
$HOME/.fehbg &

touchegg &
flameshot &
onedrive --monitor --confdir ${XDG_CONFIG_HOME:-$HOME/.config}/onedrivePersonal &
onedrive --monitor --confdir ${XDG_CONFIG_HOME:-$HOME/.config}/onedriveWork &
